/**
 * One-time template build step (run manually when the parity artifacts change):
 *   node scripts/build_template.js
 *
 * Reads the extraction artifacts of the reference workbook
 * (full_cell_data.json + parity_spec.json, produced from
 * fc_estimate_builder_robotic_tkr_unilateral_right_cash_tr1.xlsx) and emits:
 *   - src/modules/workbook/template.json  — per sheet: layout (widths, heights,
 *     hidden cols, gridlines, autofilter, validations), full cell map
 *     (value / formula+cached result / style token) and a deduped style table.
 *   - src/modules/workbook/texts.js       — long note/instruction strings as
 *     named constants (referenced from template.json via {t:key}).
 *
 * The runtime generator replays this template and overrides the DATA BANDS
 * from the live engine payload (see src/modules/workbook/bands.js).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRATCH = '/private/tmp/claude-501/-Users-apple-workspace-code-Hospital_OS/7423305f-e4f7-4d04-b8a5-29b0983a823e/scratchpad';
const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(here, '..', 'src', 'modules', 'workbook');

const fullCells = JSON.parse(fs.readFileSync(path.join(SCRATCH, 'full_cell_data.json'), 'utf8'));
const parity = JSON.parse(fs.readFileSync(path.join(SCRATCH, 'parity_spec.json'), 'utf8'));

const SHEET_ORDER = parity.workbook.sheet_names;

// AutoFilters (hidden _xlnm._FilterDatabase names — WORKBOOK_PARITY_SPEC.md)
const AUTOFILTERS = {
  'Grouping Review': 'A12:G16',
  'Estimate Breakdown': 'A3:J90',
  'Pharmacy Template': 'A3:R520',
  'Service Template': 'A3:P30',
  'Pharmacy Metrics': 'A3:R29',
  'IP FC Actuals': 'A4:AF30',
};

// ---- style table (dedup) ----
const styleTable = [];
const styleIndex = new Map();
function styleToken(cell) {
  const s = {};
  for (const k of Object.keys(cell)) {
    if (k === 'a' || k === 'v' || k === 'f' || k === 'cached') continue; // style-only keys (font/fill/border/align/nf)
    s[k] = cell[k];
  }
  if (!Object.keys(s).length) return undefined;
  const key = JSON.stringify(s);
  if (!styleIndex.has(key)) {
    styleIndex.set(key, styleTable.length);
    styleTable.push(s);
  }
  return styleIndex.get(key);
}

// ---- long text extraction ----
const texts = {};
const textIndex = new Map();
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
function textKey(sheet, addr, str) {
  if (textIndex.has(str)) return textIndex.get(str);
  const key = `${slug(sheet)}_${addr}`;
  texts[key] = str;
  textIndex.set(str, key);
  return key;
}

const template = { sheetOrder: SHEET_ORDER, styles: styleTable, sheets: {} };

for (const name of SHEET_ORDER) {
  const spec = parity.sheets[name];
  const cellsIn = fullCells[name] || {};

  // column widths / hidden
  const cols = {};
  for (const [letter, w] of Object.entries(spec.col_widths || {})) {
    cols[letter] = typeof w === 'object' ? { w: w.width, hidden: !!w.hidden } : { w };
  }

  // styled-cell map: addr -> style token
  const styleByAddr = {};
  for (const c of spec.cells || []) {
    const tok = styleToken(c);
    if (tok !== undefined) styleByAddr[c.a] = tok;
  }

  // cell map
  const cells = {};
  for (const [addr, raw] of Object.entries(cellsIn)) {
    const entry = {};
    if (raw !== null && typeof raw === 'object' && 'f' in raw) {
      entry.f = raw.f.startsWith('=') ? raw.f.slice(1) : raw.f;
      if (raw.v !== undefined && raw.v !== null) entry.r = raw.v;
    } else if (typeof raw === 'string' && raw.length >= 100) {
      entry.t = textKey(name, addr, raw);
    } else if (raw !== null && raw !== undefined) {
      entry.v = raw;
    }
    if (styleByAddr[addr] !== undefined) entry.s = styleByAddr[addr];
    if (Object.keys(entry).length) cells[addr] = entry;
  }
  // styled-but-empty cells (fills on blank cells, e.g. title bars)
  for (const [addr, tok] of Object.entries(styleByAddr)) {
    if (!cells[addr]) cells[addr] = { s: tok };
  }

  template.sheets[name] = {
    dims: spec.dimensions,
    gridlines: !!spec.show_gridlines,
    zoom: spec.zoom ?? 100,
    cols,
    rowHeights: spec.row_heights || {},
    autoFilter: AUTOFILTERS[name] || null,
    validations: (spec.data_validations || []).map((dv) => ({
      sqref: dv.sqref,
      type: dv.type,
      formula1: dv.formula1,
      allowBlank: !!dv.allow_blank,
    })),
    cells,
  };
}

fs.writeFileSync(path.join(outDir, 'template.json'), JSON.stringify(template));

const textsJs = [
  '/**',
  ' * Long note/instruction strings of the FC Estimate Builder workbook,',
  ' * extracted VERBATIM from the reference file',
  ' * fc_estimate_builder_robotic_tkr_unilateral_right_cash_tr1.xlsx.',
  ' * Referenced from template.json cells via {t: <key>}.',
  ' * AUTO-GENERATED by scripts/build_template.js — do not edit by hand.',
  ' */',
  'export const TEXTS = ' + JSON.stringify(texts, null, 1) + ';',
  '',
].join('\n');
fs.writeFileSync(path.join(outDir, 'texts.js'), textsJs);

const nCells = Object.values(template.sheets).reduce((a, s) => a + Object.keys(s.cells).length, 0);
console.log(`template.json: ${SHEET_ORDER.length} sheets, ${nCells} cells, ${styleTable.length} styles, ${Object.keys(texts).length} texts`);
console.log(`bytes: ${fs.statSync(path.join(outDir, 'template.json')).size}`);
